import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"; 
import localFont from "next/font/local";


const k2d = localFont({
  variable: "--font-k2d",
  display: "swap",
  src: [
    { path: "/fonts/k2d/K2D-Thin.woff2", weight: "100", style: "normal" },
    { path: "/fonts/k2d/K2D-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "/fonts/k2d/K2D-Light.woff2", weight: "300", style: "normal" },
    { path: "/fonts/k2d/K2D-Regular.woff2", weight: "400", style: "normal" },
    { path: "/fonts/k2d/K2D-Medium.woff2", weight: "500", style: "normal" },
    { path: "/fonts/k2d/K2D-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "/fonts/k2d/K2D-Bold.woff2", weight: "700", style: "normal" },
    { path: "/fonts/k2d/K2D-ExtraBold.woff2", weight: "800", style: "normal" },
  ],
});

const bebasNeue = localFont({
  variable: "--font-bebas-neue",
  display: "swap",
  src: [
    {
      path: "/fonts/bebas-neue/BebasNeue-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${k2d.variable} antialiased`}
      >

        {children}
        <Toaster position="top-right" richColors />
       
      </body>
    </html>
  );
}
